// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GerantReqProto.proto

package com.fireflyi.gn.gerant.domain.protobuf;

public final class GerantReqProtobuf {
  private GerantReqProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   **
   * 聊天类型
   * </pre>
   *
   * Protobuf enum {@code protocol.ChatType}
   */
  public enum ChatType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *群聊
     * </pre>
     *
     * <code>CHAT_TYPE_PUBLIC = 0;</code>
     */
    CHAT_TYPE_PUBLIC(0),
    /**
     * <pre>
     *私聊
     * </pre>
     *
     * <code>CHAT_TYPE_PRIVATE = 1;</code>
     */
    CHAT_TYPE_PRIVATE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *群聊
     * </pre>
     *
     * <code>CHAT_TYPE_PUBLIC = 0;</code>
     */
    public static final int CHAT_TYPE_PUBLIC_VALUE = 0;
    /**
     * <pre>
     *私聊
     * </pre>
     *
     * <code>CHAT_TYPE_PRIVATE = 1;</code>
     */
    public static final int CHAT_TYPE_PRIVATE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ChatType valueOf(int value) {
      return forNumber(value);
    }

    public static ChatType forNumber(int value) {
      switch (value) {
        case 0: return CHAT_TYPE_PUBLIC;
        case 1: return CHAT_TYPE_PRIVATE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ChatType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ChatType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ChatType>() {
            public ChatType findValueByNumber(int number) {
              return ChatType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return GerantReqProtobuf.getDescriptor().getEnumTypes().get(0);
    }

    private static final ChatType[] VALUES = values();

    public static ChatType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ChatType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protocol.ChatType)
  }

  public interface GerantReqProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.GerantReqProtocol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息发送时间
     * </pre>
     *
     * <code>int64 time = 1;</code>
     */
    long getTime();

    /**
     * <pre>
     *聊天类型
     * </pre>
     *
     * <code>.protocol.ChatType type = 2;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     *聊天类型
     * </pre>
     *
     * <code>.protocol.ChatType type = 2;</code>
     */
    ChatType getType();

    /**
     * <code>string reqMsg = 3;</code>
     */
    String getReqMsg();
    /**
     * <code>string reqMsg = 3;</code>
     */
    com.google.protobuf.ByteString
        getReqMsgBytes();

    /**
     * <pre>
     *目标用户id，
     * </pre>
     *
     * <code>int32 reqId = 4;</code>
     */
    int getReqId();
  }
  /**
   * Protobuf type {@code protocol.GerantReqProtocol}
   */
  public  static final class GerantReqProtocol extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.GerantReqProtocol)
      GerantReqProtocolOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GerantReqProtocol.newBuilder() to construct.
    private GerantReqProtocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GerantReqProtocol() {
      type_ = 0;
      reqMsg_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new GerantReqProtocol();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GerantReqProtocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              time_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              reqMsg_ = s;
              break;
            }
            case 32: {

              reqId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GerantReqProtobuf.internal_static_protocol_GerantReqProtocol_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GerantReqProtobuf.internal_static_protocol_GerantReqProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GerantReqProtocol.class, Builder.class);
    }

    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    /**
     * <pre>
     *消息发送时间
     * </pre>
     *
     * <code>int64 time = 1;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <pre>
     *聊天类型
     * </pre>
     *
     * <code>.protocol.ChatType type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     *聊天类型
     * </pre>
     *
     * <code>.protocol.ChatType type = 2;</code>
     */
    public ChatType getType() {
      @SuppressWarnings("deprecation")
      ChatType result = ChatType.valueOf(type_);
      return result == null ? ChatType.UNRECOGNIZED : result;
    }

    public static final int REQMSG_FIELD_NUMBER = 3;
    private volatile Object reqMsg_;
    /**
     * <code>string reqMsg = 3;</code>
     */
    public String getReqMsg() {
      Object ref = reqMsg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        reqMsg_ = s;
        return s;
      }
    }
    /**
     * <code>string reqMsg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getReqMsgBytes() {
      Object ref = reqMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        reqMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQID_FIELD_NUMBER = 4;
    private int reqId_;
    /**
     * <pre>
     *目标用户id，
     * </pre>
     *
     * <code>int32 reqId = 4;</code>
     */
    public int getReqId() {
      return reqId_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (time_ != 0L) {
        output.writeInt64(1, time_);
      }
      if (type_ != ChatType.CHAT_TYPE_PUBLIC.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (!getReqMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, reqMsg_);
      }
      if (reqId_ != 0) {
        output.writeInt32(4, reqId_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, time_);
      }
      if (type_ != ChatType.CHAT_TYPE_PUBLIC.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (!getReqMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, reqMsg_);
      }
      if (reqId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, reqId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GerantReqProtocol)) {
        return super.equals(obj);
      }
      GerantReqProtocol other = (GerantReqProtocol) obj;

      if (getTime()
          != other.getTime()) return false;
      if (type_ != other.type_) return false;
      if (!getReqMsg()
          .equals(other.getReqMsg())) return false;
      if (getReqId()
          != other.getReqId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + REQMSG_FIELD_NUMBER;
      hash = (53 * hash) + getReqMsg().hashCode();
      hash = (37 * hash) + REQID_FIELD_NUMBER;
      hash = (53 * hash) + getReqId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GerantReqProtocol parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GerantReqProtocol parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GerantReqProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GerantReqProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GerantReqProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GerantReqProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GerantReqProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GerantReqProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GerantReqProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GerantReqProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GerantReqProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GerantReqProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GerantReqProtocol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.GerantReqProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.GerantReqProtocol)
        GerantReqProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GerantReqProtobuf.internal_static_protocol_GerantReqProtocol_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GerantReqProtobuf.internal_static_protocol_GerantReqProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GerantReqProtocol.class, Builder.class);
      }

      // Construct using com.fireflyi.gn.gerant.domain.protobuf.GerantReqProtobuf.GerantReqProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        time_ = 0L;

        type_ = 0;

        reqMsg_ = "";

        reqId_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GerantReqProtobuf.internal_static_protocol_GerantReqProtocol_descriptor;
      }

      @Override
      public GerantReqProtocol getDefaultInstanceForType() {
        return GerantReqProtocol.getDefaultInstance();
      }

      @Override
      public GerantReqProtocol build() {
        GerantReqProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public GerantReqProtocol buildPartial() {
        GerantReqProtocol result = new GerantReqProtocol(this);
        result.time_ = time_;
        result.type_ = type_;
        result.reqMsg_ = reqMsg_;
        result.reqId_ = reqId_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GerantReqProtocol) {
          return mergeFrom((GerantReqProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GerantReqProtocol other) {
        if (other == GerantReqProtocol.getDefaultInstance()) return this;
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getReqMsg().isEmpty()) {
          reqMsg_ = other.reqMsg_;
          onChanged();
        }
        if (other.getReqId() != 0) {
          setReqId(other.getReqId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GerantReqProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GerantReqProtocol) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long time_ ;
      /**
       * <pre>
       *消息发送时间
       * </pre>
       *
       * <code>int64 time = 1;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <pre>
       *消息发送时间
       * </pre>
       *
       * <code>int64 time = 1;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息发送时间
       * </pre>
       *
       * <code>int64 time = 1;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       *聊天类型
       * </pre>
       *
       * <code>.protocol.ChatType type = 2;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       *聊天类型
       * </pre>
       *
       * <code>.protocol.ChatType type = 2;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *聊天类型
       * </pre>
       *
       * <code>.protocol.ChatType type = 2;</code>
       */
      public ChatType getType() {
        @SuppressWarnings("deprecation")
        ChatType result = ChatType.valueOf(type_);
        return result == null ? ChatType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *聊天类型
       * </pre>
       *
       * <code>.protocol.ChatType type = 2;</code>
       */
      public Builder setType(ChatType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *聊天类型
       * </pre>
       *
       * <code>.protocol.ChatType type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private Object reqMsg_ = "";
      /**
       * <code>string reqMsg = 3;</code>
       */
      public String getReqMsg() {
        Object ref = reqMsg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          reqMsg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string reqMsg = 3;</code>
       */
      public com.google.protobuf.ByteString
          getReqMsgBytes() {
        Object ref = reqMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          reqMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reqMsg = 3;</code>
       */
      public Builder setReqMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reqMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string reqMsg = 3;</code>
       */
      public Builder clearReqMsg() {
        
        reqMsg_ = getDefaultInstance().getReqMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string reqMsg = 3;</code>
       */
      public Builder setReqMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reqMsg_ = value;
        onChanged();
        return this;
      }

      private int reqId_ ;
      /**
       * <pre>
       *目标用户id，
       * </pre>
       *
       * <code>int32 reqId = 4;</code>
       */
      public int getReqId() {
        return reqId_;
      }
      /**
       * <pre>
       *目标用户id，
       * </pre>
       *
       * <code>int32 reqId = 4;</code>
       */
      public Builder setReqId(int value) {
        
        reqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目标用户id，
       * </pre>
       *
       * <code>int32 reqId = 4;</code>
       */
      public Builder clearReqId() {
        
        reqId_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.GerantReqProtocol)
    }

    // @@protoc_insertion_point(class_scope:protocol.GerantReqProtocol)
    private static final GerantReqProtocol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GerantReqProtocol();
    }

    public static GerantReqProtocol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GerantReqProtocol>
        PARSER = new com.google.protobuf.AbstractParser<GerantReqProtocol>() {
      @Override
      public GerantReqProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GerantReqProtocol(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GerantReqProtocol> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GerantReqProtocol> getParserForType() {
      return PARSER;
    }

    @Override
    public GerantReqProtocol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_GerantReqProtocol_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_GerantReqProtocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024GerantReqProto.proto\022\010protocol\"b\n\021Gera" +
      "ntReqProtocol\022\014\n\004time\030\001 \001(\003\022 \n\004type\030\002 \001(" +
      "\0162\022.protocol.ChatType\022\016\n\006reqMsg\030\003 \001(\t\022\r\n" +
      "\005reqId\030\004 \001(\005*7\n\010ChatType\022\024\n\020CHAT_TYPE_PU" +
      "BLIC\020\000\022\025\n\021CHAT_TYPE_PRIVATE\020\001B;\n&com.fir" +
      "eflyi.gn.gerant.domain.protobufB\021GerantR" +
      "eqProtobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_GerantReqProtocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_GerantReqProtocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_GerantReqProtocol_descriptor,
        new String[] { "Time", "Type", "ReqMsg", "ReqId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
