// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Greqptc.proto

package com.fireflyi.gerant.rpclient.protobuf;

public final class GreqPtc {
  private GreqPtc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_Greq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_Greq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rGreqptc.proto\022\010protocol\"B\n\004Greq\022\r\n\005cmd" +
      "Id\030\001 \001(\t\022\016\n\006reqMsg\030\002 \001(\t\022\r\n\005objId\030\003 \001(\005\022" +
      "\014\n\004time\030\004 \001(\003B2\n%com.fireflyi.gerant.rpc" +
      "lient.protobufB\007GreqPtcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_Greq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_Greq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_Greq_descriptor,
        new java.lang.String[] { "CmdId", "ReqMsg", "ObjId", "Time", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
