// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Greqptc.proto

package com.fireflyi.gerant.rpclient.protobuf;

/**
 * Protobuf type {@code protocol.Greq}
 */
public  final class Greq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protocol.Greq)
    GreqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Greq.newBuilder() to construct.
  private Greq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Greq() {
    type_ = 0;
    reqMsg_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Greq();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Greq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            time_ = input.readInt64();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            reqMsg_ = s;
            break;
          }
          case 32: {

            objId_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.fireflyi.gerant.rpclient.protobuf.GreqPtc.internal_static_protocol_Greq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.fireflyi.gerant.rpclient.protobuf.GreqPtc.internal_static_protocol_Greq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.fireflyi.gerant.rpclient.protobuf.Greq.class, com.fireflyi.gerant.rpclient.protobuf.Greq.Builder.class);
  }

  public static final int TIME_FIELD_NUMBER = 1;
  private long time_;
  /**
   * <pre>
   *消息发送时间
   * </pre>
   *
   * <code>int64 time = 1;</code>
   */
  public long getTime() {
    return time_;
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private int type_;
  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>.protocol.ChatType type = 2;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>.protocol.ChatType type = 2;</code>
   */
  public com.fireflyi.gerant.rpclient.protobuf.ChatType getType() {
    @SuppressWarnings("deprecation")
    com.fireflyi.gerant.rpclient.protobuf.ChatType result = com.fireflyi.gerant.rpclient.protobuf.ChatType.valueOf(type_);
    return result == null ? com.fireflyi.gerant.rpclient.protobuf.ChatType.UNRECOGNIZED : result;
  }

  public static final int REQMSG_FIELD_NUMBER = 3;
  private volatile java.lang.Object reqMsg_;
  /**
   * <code>string reqMsg = 3;</code>
   */
  public java.lang.String getReqMsg() {
    java.lang.Object ref = reqMsg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reqMsg_ = s;
      return s;
    }
  }
  /**
   * <code>string reqMsg = 3;</code>
   */
  public com.google.protobuf.ByteString
      getReqMsgBytes() {
    java.lang.Object ref = reqMsg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reqMsg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OBJID_FIELD_NUMBER = 4;
  private int objId_;
  /**
   * <pre>
   *目标id
   * </pre>
   *
   * <code>int32 objId = 4;</code>
   */
  public int getObjId() {
    return objId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (time_ != 0L) {
      output.writeInt64(1, time_);
    }
    if (type_ != com.fireflyi.gerant.rpclient.protobuf.ChatType.CHAT_TYPE_PUBLIC.getNumber()) {
      output.writeEnum(2, type_);
    }
    if (!getReqMsgBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, reqMsg_);
    }
    if (objId_ != 0) {
      output.writeInt32(4, objId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (time_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, time_);
    }
    if (type_ != com.fireflyi.gerant.rpclient.protobuf.ChatType.CHAT_TYPE_PUBLIC.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, type_);
    }
    if (!getReqMsgBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, reqMsg_);
    }
    if (objId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, objId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.fireflyi.gerant.rpclient.protobuf.Greq)) {
      return super.equals(obj);
    }
    com.fireflyi.gerant.rpclient.protobuf.Greq other = (com.fireflyi.gerant.rpclient.protobuf.Greq) obj;

    if (getTime()
        != other.getTime()) return false;
    if (type_ != other.type_) return false;
    if (!getReqMsg()
        .equals(other.getReqMsg())) return false;
    if (getObjId()
        != other.getObjId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTime());
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + REQMSG_FIELD_NUMBER;
    hash = (53 * hash) + getReqMsg().hashCode();
    hash = (37 * hash) + OBJID_FIELD_NUMBER;
    hash = (53 * hash) + getObjId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.fireflyi.gerant.rpclient.protobuf.Greq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fireflyi.gerant.rpclient.protobuf.Greq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fireflyi.gerant.rpclient.protobuf.Greq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fireflyi.gerant.rpclient.protobuf.Greq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fireflyi.gerant.rpclient.protobuf.Greq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fireflyi.gerant.rpclient.protobuf.Greq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fireflyi.gerant.rpclient.protobuf.Greq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fireflyi.gerant.rpclient.protobuf.Greq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fireflyi.gerant.rpclient.protobuf.Greq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.fireflyi.gerant.rpclient.protobuf.Greq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fireflyi.gerant.rpclient.protobuf.Greq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fireflyi.gerant.rpclient.protobuf.Greq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.fireflyi.gerant.rpclient.protobuf.Greq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protocol.Greq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.Greq)
      com.fireflyi.gerant.rpclient.protobuf.GreqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fireflyi.gerant.rpclient.protobuf.GreqPtc.internal_static_protocol_Greq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fireflyi.gerant.rpclient.protobuf.GreqPtc.internal_static_protocol_Greq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fireflyi.gerant.rpclient.protobuf.Greq.class, com.fireflyi.gerant.rpclient.protobuf.Greq.Builder.class);
    }

    // Construct using com.fireflyi.gerant.rpclient.protobuf.Greq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      time_ = 0L;

      type_ = 0;

      reqMsg_ = "";

      objId_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.fireflyi.gerant.rpclient.protobuf.GreqPtc.internal_static_protocol_Greq_descriptor;
    }

    @java.lang.Override
    public com.fireflyi.gerant.rpclient.protobuf.Greq getDefaultInstanceForType() {
      return com.fireflyi.gerant.rpclient.protobuf.Greq.getDefaultInstance();
    }

    @java.lang.Override
    public com.fireflyi.gerant.rpclient.protobuf.Greq build() {
      com.fireflyi.gerant.rpclient.protobuf.Greq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.fireflyi.gerant.rpclient.protobuf.Greq buildPartial() {
      com.fireflyi.gerant.rpclient.protobuf.Greq result = new com.fireflyi.gerant.rpclient.protobuf.Greq(this);
      result.time_ = time_;
      result.type_ = type_;
      result.reqMsg_ = reqMsg_;
      result.objId_ = objId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.fireflyi.gerant.rpclient.protobuf.Greq) {
        return mergeFrom((com.fireflyi.gerant.rpclient.protobuf.Greq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.fireflyi.gerant.rpclient.protobuf.Greq other) {
      if (other == com.fireflyi.gerant.rpclient.protobuf.Greq.getDefaultInstance()) return this;
      if (other.getTime() != 0L) {
        setTime(other.getTime());
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (!other.getReqMsg().isEmpty()) {
        reqMsg_ = other.reqMsg_;
        onChanged();
      }
      if (other.getObjId() != 0) {
        setObjId(other.getObjId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.fireflyi.gerant.rpclient.protobuf.Greq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.fireflyi.gerant.rpclient.protobuf.Greq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long time_ ;
    /**
     * <pre>
     *消息发送时间
     * </pre>
     *
     * <code>int64 time = 1;</code>
     */
    public long getTime() {
      return time_;
    }
    /**
     * <pre>
     *消息发送时间
     * </pre>
     *
     * <code>int64 time = 1;</code>
     */
    public Builder setTime(long value) {
      
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *消息发送时间
     * </pre>
     *
     * <code>int64 time = 1;</code>
     */
    public Builder clearTime() {
      
      time_ = 0L;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <pre>
     *聊天类型
     * </pre>
     *
     * <code>.protocol.ChatType type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     *聊天类型
     * </pre>
     *
     * <code>.protocol.ChatType type = 2;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *聊天类型
     * </pre>
     *
     * <code>.protocol.ChatType type = 2;</code>
     */
    public com.fireflyi.gerant.rpclient.protobuf.ChatType getType() {
      @SuppressWarnings("deprecation")
      com.fireflyi.gerant.rpclient.protobuf.ChatType result = com.fireflyi.gerant.rpclient.protobuf.ChatType.valueOf(type_);
      return result == null ? com.fireflyi.gerant.rpclient.protobuf.ChatType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *聊天类型
     * </pre>
     *
     * <code>.protocol.ChatType type = 2;</code>
     */
    public Builder setType(com.fireflyi.gerant.rpclient.protobuf.ChatType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *聊天类型
     * </pre>
     *
     * <code>.protocol.ChatType type = 2;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object reqMsg_ = "";
    /**
     * <code>string reqMsg = 3;</code>
     */
    public java.lang.String getReqMsg() {
      java.lang.Object ref = reqMsg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reqMsg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string reqMsg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getReqMsgBytes() {
      java.lang.Object ref = reqMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string reqMsg = 3;</code>
     */
    public Builder setReqMsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      reqMsg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string reqMsg = 3;</code>
     */
    public Builder clearReqMsg() {
      
      reqMsg_ = getDefaultInstance().getReqMsg();
      onChanged();
      return this;
    }
    /**
     * <code>string reqMsg = 3;</code>
     */
    public Builder setReqMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      reqMsg_ = value;
      onChanged();
      return this;
    }

    private int objId_ ;
    /**
     * <pre>
     *目标id
     * </pre>
     *
     * <code>int32 objId = 4;</code>
     */
    public int getObjId() {
      return objId_;
    }
    /**
     * <pre>
     *目标id
     * </pre>
     *
     * <code>int32 objId = 4;</code>
     */
    public Builder setObjId(int value) {
      
      objId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *目标id
     * </pre>
     *
     * <code>int32 objId = 4;</code>
     */
    public Builder clearObjId() {
      
      objId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protocol.Greq)
  }

  // @@protoc_insertion_point(class_scope:protocol.Greq)
  private static final com.fireflyi.gerant.rpclient.protobuf.Greq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.fireflyi.gerant.rpclient.protobuf.Greq();
  }

  public static com.fireflyi.gerant.rpclient.protobuf.Greq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Greq>
      PARSER = new com.google.protobuf.AbstractParser<Greq>() {
    @java.lang.Override
    public Greq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Greq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Greq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Greq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.fireflyi.gerant.rpclient.protobuf.Greq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

