// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Gresptc.proto

package com.fireflyi.gerant.rpclient.protobuf;

public final class GresPtc {
  private GresPtc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_Gres_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_Gres_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rGresptc.proto\022\010protocol\"4\n\004Gres\022\016\n\006sta" +
      "tus\030\001 \001(\005\022\014\n\004code\030\002 \001(\005\022\016\n\006resMsg\030\003 \001(\tB" +
      "2\n%com.fireflyi.gerant.rpclient.protobuf" +
      "B\007GresPtcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_Gres_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_Gres_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_Gres_descriptor,
        new java.lang.String[] { "Status", "Code", "ResMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
